
services:
  - type: web
    name: prohire-java-backend
    runtime: docker
    envVars:
      - key: PORT
        value: 8080
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://ep-lingering-pond-b5llvv1n-pooler.c-7.us-east-2.aws.neon.tech/neondb?sslmode=require
      - key: SPRING_DATASOURCE_USERNAME
        value: neondb_owner
      - key: SPRING_DATASOURCE_PASSWORD
        value: npg_LbJhYKT8O4yR
      - key: SPRING_DATASOURCE_DRIVER_CLASS_NAME
        value: org.postgresql.Driver
      - key: SPRING_JPA_DATABASE_PLATFORM
        value: org.hibernate.dialect.PostgreSQLDialect
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update
      - key: PROHIRE_JWT_SECRET
        value: super-secret-key-that-is-at-least-32-characters-long
      - key: NEON_AUTH_URL
        value: https://ep-lingering-pond-b5llvv1n.neonauth.c-7.us-east-2.aws.neon.tech/neondb/auth
      - key: NEON_JWKS_URI
        value: https://ep-lingering-pond-b5llvv1n.neonauth.c-7.us-east-2.aws.neon.tech/neondb/auth/.well-known/jwks.json
      - key: NEON_REST_URL
        value: https://ep-lingering-pond-b5llvv1n.apirest.c-7.us-east-2.aws.neon.tech/neondb/rest/v1



